// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      databaseURL:
          'https://hcm2303-default-rtdb.asia-southeast1.firebasedatabase.app',
      apiKey: "AIzaSyCaIMghGiqalK5qY7xfE1PwtC5T2SeIPBQ",
      authDomain: "todoapp-2659e.firebaseapp.com",
      projectId: "todoapp-2659e",
      storageBucket: "todoapp-2659e.appspot.com",
      messagingSenderId: "217897542997",
      appId: "1:217897542997:web:db3f03fb89680d51973bdc",
      measurementId: "G-HXDZ3J28LS");

  static const FirebaseOptions android = FirebaseOptions(
      databaseURL: 'https://todoapp-2659e-default-rtdb.firebaseio.com',
      apiKey: "AIzaSyCaIMghGiqalK5qY7xfE1PwtC5T2SeIPBQ",
      authDomain: "todoapp-2659e.firebaseapp.com",
      projectId: "todoapp-2659e",
      storageBucket: "todoapp-2659e.appspot.com",
      messagingSenderId: "217897542997",
      appId: "1:217897542997:web:db3f03fb89680d51973bdc",
      measurementId: "G-HXDZ3J28LS");

  static const FirebaseOptions ios = FirebaseOptions(
      databaseURL: 'https://todoapp-2659e-default-rtdb.firebaseio.com',
      iosClientId:
          '561058666320-seq1b5adkh0o0ucjhv91end8l3plcbrs.apps.googleusercontent.com',
      iosBundleId: 'dat3023.dev.todo.appliction',
      apiKey: "AIzaSyCaIMghGiqalK5qY7xfE1PwtC5T2SeIPBQ",
      authDomain: "todoapp-2659e.firebaseapp.com",
      projectId: "todoapp-2659e",
      storageBucket: "todoapp-2659e.appspot.com",
      messagingSenderId: "217897542997",
      appId: "1:217897542997:web:db3f03fb89680d51973bdc",
      measurementId: "G-HXDZ3J28LS");

  static const FirebaseOptions macos = FirebaseOptions(
      databaseURL: 'https://todoapp-2659e-default-rtdb.firebaseio.com',
      iosClientId:
          '561058666320-mm5bc21p08jcn66mmp4ss9vifv8epsng.apps.googleusercontent.com',
      iosBundleId: 'com.example.hcm2303',
      apiKey: "AIzaSyCaIMghGiqalK5qY7xfE1PwtC5T2SeIPBQ",
      authDomain: "todoapp-2659e.firebaseapp.com",
      projectId: "todoapp-2659e",
      storageBucket: "todoapp-2659e.appspot.com",
      messagingSenderId: "217897542997",
      appId: "1:217897542997:web:db3f03fb89680d51973bdc",
      measurementId: "G-HXDZ3J28LS");
}
